#ifndef __FLAT_DRAW_ERROR_CALL_LIBRARY_H_INCLUDED__
#define __FLAT_DRAW_ERROR_CALL_LIBRARY_H_INCLUDED__

void el_set_par_window(GtkWidget *window);

void el_call_error(int err_type);
void el_call_dialog(char *msg);

enum ERROR_TYPES {
	ET_WRONG_SELECTING = 0,
	ET_CREATE_OPTIONS_FAIL,
	ET_WRONG_DATA,
	ET_FAIL_TO_OPEN_FILE,
	ET_FAIL_TO_CREATE_FIGURE,
	ET_FAIL_TO_CREATE_LIST_NODE,
	ET_FAIL_TO_RUN_PLUGIN,
	ET_FAIL_TO_CREATE_TEXT_OBJECT,
	ET_FAIL_TO_ALLOCATE_MEMORY_FOR_FONT,
	ET_FAIL_TO_ALLOCATE_MEMORY_FOR_TEXT_BUFFER
};

#endif
